In [ ]:
#Importamos librerias
import numpy as np
import pandas as pd
from sklearn import tree
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.decomposition import PCA
from sklearn.tree import DecisionTreeClassifier, export_graphviz #Libreria de arbol de decisiones

In [ ]:
# Cargar el conjunto de datos en un DataFrame
df = pd.read_csv('/content/drive/MyDrive/Practica Diplomado/Entrenamiento de modelos/StressLevelDataset.csv')
df

anxiety_level  self_esteem  mental_health_history  depression  headache  \
0                14           20                      0          11         2   
1                15            8                      1          15         5   
2                12           18                      1          14         2   
3                16           12                      1          15         4   
4                16           28                      0           7         2   
...             ...          ...                    ...         ...       ...   
1095             11           17                      0          14         3   
1096              9           12                      0           8         0   
1097              4           26                      0           3         1   
1098             21            0                      1          19         5   
1099             18            6                      1          15         3   

      blood_pressure  sleep_quality  breathing_problem  noise_level  \
0                  1              2                  4            2   
1                  3              1                  4            3   
2                  1              2                  2            2   
3                  3              1                  3            4   
4                  3              5                  1            3   
...              ...            ...                ...          ...   
1095               1              3                  2            2   
1096               3              0                  0            0   
1097               2              5                  2            2   
1098               3              1                  4            3   
1099               3              0                  3            3   

      living_conditions  ...  basic_needs  academic_performance  study_load  \
0                     3  ...            2                     3           2   
1                     1  ...            2                     1           4   
2                     2  ...            2                     2           3   
3                     2  ...            2                     2           4   
4                     2  ...            3                     4           3   
...                 ...  ...          ...                   ...         ...   
1095                  2  ...            3                     2           2   
1096                  1  ...            4                     0           1   
1097                  3  ...            4                     5           1   
1098                  1  ...            1                     2           5   
1099                  0  ...            3                     3           4   

      teacher_student_relationship  future_career_concerns  social_support  \
0                                3                       3               2   
1                                1                       5               1   
2                                3                       2               2   
3                                1                       4               1   
4                                1                       2               1   
...                            ...                     ...             ...   
1095                             2                       3               3   
1096                             1                       1               1   
1097                             4                       1               3   
1098                             1                       4               1   
1099                             3                       3               1   

      peer_pressure  extracurricular_activities  bullying  stress_level  
0                 3                           3         2             1  
1                 4                           5         5             2  
2                 3                           2         2             1 

In [ ]:
#Miramos la cantidad de estudiantes según el rango de estrés
estresEst = df['stress_level'].value_counts()
print("Estudiantes según el rango de estrés:\n",estresEst)

Estudiantes según el rango de estrés:
 stress_level
0    373
2    369
1    358
Name: count, dtype: int64


In [ ]:
#Creamos nuestro vector de variables independientes (caracteristicas)
x = df.drop(['stress_level'],axis = 1)
print("Caracteristicas originales:\n",x)

Caracteristicas originales:
       anxiety_level  self_esteem  mental_health_history  depression  headache  \
0                14           20                      0          11         2   
1                15            8                      1          15         5   
2                12           18                      1          14         2   
3                16           12                      1          15         4   
4                16           28                      0           7         2   
...             ...          ...                    ...         ...       ...   
1095             11           17                      0          14         3   
1096              9           12                      0           8         0   
1097              4           26                      0           3         1   
1098             21            0                      1          19         5   
1099             18            6                      1          15         3   

In [ ]:
#Creamos nuestro vector de etiquetas(stress_level)
y = df.stress_level
y

0       1
1       2
2       1
3       2
4       1
       ..
1095    1
1096    2
1097    0
1098    2
1099    2
Name: stress_level, Length: 1100, dtype: int64

In [ ]:
#Creamos nuestros sets de entrenamiento
from sklearn.model_selection import train_test_split #Importamos librerias
x_entre, x_test, y_entre, y_test = train_test_split(x, y, test_size=0.3, random_state=2024)
#En este caso vamos a utilizar el 30% de testeo y el 70% para entreno

In [ ]:
std=StandardScaler()
std.fit(x_entre)

StandardScaler()

In [ ]:
x_entret=std.transform(x_entre)
y_testt=std.transform(x_test)

In [ ]:
x_entret

array([[ 0.27995069, -0.18853456,  1.00520837, ...,  0.16889533,
         0.15441098, -0.40832766],
       [-1.18979042,  0.81418571, -0.99481862, ..., -0.53029501,
        -1.26102302, -1.04998542],
       [-1.02648586,  1.37125252, -0.99481862, ..., -1.22948534,
        -1.26102302, -1.04998542],
       ...,
       [ 1.58638723, -1.74832165,  1.00520837, ...,  0.86808566,
         0.86212798,  0.87498785],
       [-1.02648586,  1.37125252, -0.99481862, ..., -1.22948534,
        -1.26102302, -1.04998542],
       [ 0.11664612,  0.47994562, -0.99481862, ..., -0.53029501,
        -0.55330602,  0.23333009]])

In [ ]:
arbol=DecisionTreeClassifier()

In [ ]:
arbol.fit(x_entre,y_entre)
arbol.score(x_test,y_test)

0.8787878787878788

# Three Transformation

1. Standard Scaler
2. PCA
3. Decision Tree Classifier

In [ ]:
std=StandardScaler()
std.fit(x_entre)

StandardScaler()

In [ ]:
Xtrain_t=std.transform(x_entre)
Xtest_t=std.transform(x_test)

In [ ]:
pca=PCA(n_components=10)
pca.fit(Xtrain_t)


PCA(n_components=10)

In [ ]:
Xtrain_tr=pca.transform(Xtrain_t)
Xtest_tr=pca.transform(Xtest_t)

Xtrain_t.shape,Xtrain_tr.shape

((770, 20), (770, 10))

In [ ]:
arbol=DecisionTreeClassifier()
arbol.fit(Xtrain_tr,y_entre)
arbol.score(Xtest_tr,y_test)

0.9030303030303031

# Error prediction model

In [ ]:
arbol.predict(
    pca.transform(
        std.transform([
    [6,	8, 0, 27, 4, 3, 1, 2, 0, 5, 2, 2, 2, 2, 1, 5, 1, 5, 3, 4],
    [21, 1,	1, 25, 4, 3, 1, 4, 4, 1, 2, 1, 1, 5, 2, 5, 1, 4, 4, 5],
    [17, 6, 1, 24, 3, 3, 1, 3, 5, 1, 1, 1, 2, 3, 1, 4, 1, 4, 5, 4],
    [5, 25, 0, 6, 1, 2, 5, 1, 1, 4, 4, 4, 5, 1, 4, 1, 3, 1, 1, 1],
    [2, 26, 0, 4, 1, 2, 5, 2, 1, 4, 4, 5, 4, 2, 5, 1, 3, 2, 2, 1],
    [4, 27, 0, 5, 1, 2, 4, 2, 1, 4, 4, 5, 5, 2, 5, 1, 3, 1, 2, 1],
    [1, 26, 0, 18, 2, 3, 3, 3, 1, 2, 2, 4, 3, 2, 1, 5, 1, 1, 5, 2],
    [18, 13, 1, 23, 3, 3, 1, 3, 5, 2, 1, 1, 2, 4, 2, 5, 1, 4, 4, 4],
    [17, 12, 1, 18, 4, 3, 1, 5, 4, 2, 1, 2, 1, 4, 1, 5, 1, 5, 4, 4],
    [9, 23, 1, 13, 3, 1, 3, 4, 3, 3, 2, 2, 3, 3, 3, 2, 2, 3, 2, 3]
])))

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([1, 2, 2, 0, 0, 0, 0, 2, 2, 1])

## Save model

In [ ]:
import joblib

In [ ]:
path="/content/drive/MyDrive/Practica Diplomado/PipeLine/"
joblib.dump(arbol,path+"arbol.model")
joblib.dump(std,path+"std.model")
joblib.dump(pca,path+"pca.model")

['/content/drive/MyDrive/Practica Diplomado/PipeLine/pca.model']

## Load model

In [ ]:
path="/content/drive/MyDrive/Practica Diplomado/PipeLine/"
arbol_model=joblib.load(path+"arbol.model")
std_model=joblib.load(path+"std.model")
pca_model=joblib.load(path+"pca.model")

In [ ]:
arbol.predict(
    pca.transform(
        std.transform([
    [6,	8, 0, 27, 4, 3, 1, 2, 0, 5, 2, 2, 2, 2, 1, 5, 1, 5, 3, 4],
    [21, 1,	1, 25, 4, 3, 1, 4, 4, 1, 2, 1, 1, 5, 2, 5, 1, 4, 4, 5],
    [17, 6, 1, 24, 3, 3, 1, 3, 5, 1, 1, 1, 2, 3, 1, 4, 1, 4, 5, 4],
    [5, 25, 0, 6, 1, 2, 5, 1, 1, 4, 4, 4, 5, 1, 4, 1, 3, 1, 1, 1],
    [2, 26, 0, 4, 1, 2, 5, 2, 1, 4, 4, 5, 4, 2, 5, 1, 3, 2, 2, 1],
    [4, 27, 0, 5, 1, 2, 4, 2, 1, 4, 4, 5, 5, 2, 5, 1, 3, 1, 2, 1],
    [1, 26, 0, 18, 2, 3, 3, 3, 1, 2, 2, 4, 3, 2, 1, 5, 1, 1, 5, 2],
    [18, 13, 1, 23, 3, 3, 1, 3, 5, 2, 1, 1, 2, 4, 2, 5, 1, 4, 4, 4],
    [17, 12, 1, 18, 4, 3, 1, 5, 4, 2, 1, 2, 1, 4, 1, 5, 1, 5, 4, 4],
    [9, 23, 1, 13, 3, 1, 3, 4, 3, 3, 2, 2, 3, 3, 3, 2, 2, 3, 2, 3]
])))

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([1, 2, 2, 0, 0, 0, 0, 2, 2, 1])

#Aplicación de PipeLine

In [ ]:
from sklearn.pipeline import Pipeline

In [ ]:
pipe1=Pipeline([
    ("scaler",StandardScaler()),
     ("pca",PCA(n_components=10)),
      ("arbol",DecisionTreeClassifier())])

In [ ]:
pipe1.fit(x_entre,y_entre)
pipe1.score(x_test,y_test)

0.9030303030303031

## Prediction

In [ ]:
pipe1.predict(
    [
    [6,	8, 0, 27, 4, 3, 1, 2, 0, 5, 2, 2, 2, 2, 1, 5, 1, 5, 3, 4],
    [21, 1,	1, 25, 4, 3, 1, 4, 4, 1, 2, 1, 1, 5, 2, 5, 1, 4, 4, 5],
    [17, 6, 1, 24, 3, 3, 1, 3, 5, 1, 1, 1, 2, 3, 1, 4, 1, 4, 5, 4],
    [5, 25, 0, 6, 1, 2, 5, 1, 1, 4, 4, 4, 5, 1, 4, 1, 3, 1, 1, 1],
    [2, 26, 0, 4, 1, 2, 5, 2, 1, 4, 4, 5, 4, 2, 5, 1, 3, 2, 2, 1],
    [4, 27, 0, 5, 1, 2, 4, 2, 1, 4, 4, 5, 5, 2, 5, 1, 3, 1, 2, 1],
    [1, 26, 0, 18, 2, 3, 3, 3, 1, 2, 2, 4, 3, 2, 1, 5, 1, 1, 5, 2],
    [18, 13, 1, 23, 3, 3, 1, 3, 5, 2, 1, 1, 2, 4, 2, 5, 1, 4, 4, 4],
    [17, 12, 1, 18, 4, 3, 1, 5, 4, 2, 1, 2, 1, 4, 1, 5, 1, 5, 4, 4],
    [9, 23, 1, 13, 3, 1, 3, 4, 3, 3, 2, 2, 3, 3, 3, 2, 2, 3, 2, 3]
    ]
)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([1, 2, 2, 0, 0, 0, 0, 2, 2, 1])

## Save model

In [ ]:
path="/content/drive/MyDrive/Practica Diplomado/PipeLine/"
joblib.dump(pipe1,path+"pipe1.model")

['/content/drive/MyDrive/Practica Diplomado/PipeLine/pipe1.model']

# Load model

In [ ]:
path="/content/drive/MyDrive/Practica Diplomado/PipeLine/"
pipe1_model=joblib.load(path+"pipe1.model")

In [ ]:
pipe1_model.predict(
    [
    [6,	8, 0, 27, 4, 3, 1, 2, 0, 5, 2, 2, 2, 2, 1, 5, 1, 5, 3, 4],
    [21, 1,	1, 25, 4, 3, 1, 4, 4, 1, 2, 1, 1, 5, 2, 5, 1, 4, 4, 5],
    [17, 6, 1, 24, 3, 3, 1, 3, 5, 1, 1, 1, 2, 3, 1, 4, 1, 4, 5, 4],
    [5, 25, 0, 6, 1, 2, 5, 1, 1, 4, 4, 4, 5, 1, 4, 1, 3, 1, 1, 1],
    [2, 26, 0, 4, 1, 2, 5, 2, 1, 4, 4, 5, 4, 2, 5, 1, 3, 2, 2, 1],
    [4, 27, 0, 5, 1, 2, 4, 2, 1, 4, 4, 5, 5, 2, 5, 1, 3, 1, 2, 1],
    [1, 26, 0, 18, 2, 3, 3, 3, 1, 2, 2, 4, 3, 2, 1, 5, 1, 1, 5, 2],
    [18, 13, 1, 23, 3, 3, 1, 3, 5, 2, 1, 1, 2, 4, 2, 5, 1, 4, 4, 4],
    [17, 12, 1, 18, 4, 3, 1, 5, 4, 2, 1, 2, 1, 4, 1, 5, 1, 5, 4, 4],
    [9, 23, 1, 13, 3, 1, 3, 4, 3, 3, 2, 2, 3, 3, 3, 2, 2, 3, 2, 3]
    ]
)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([1, 2, 2, 0, 0, 0, 0, 2, 2, 1])

In [ ]:
import pickle

In [ ]:
# Grabamos el modelo en el directorio
pkl_filename = "pickle_model.pkl"
with open(pkl_filename, 'wb') as file:
    pickle.dump(pipe1_model, file)

In [ ]:
# Cargamos el modelo
pkl_filename = "pickle_model.pkl"
with open(pkl_filename, 'rb') as file:
    model = pickle.load(file)

In [ ]:
#Encontramos el accuracy promedio usando datos de test
score = model.score(x_test, y_test)
print(score)

0.9030303030303031


In [ ]:
model.predict(
    [
    [0, 25, 0, 4, 1, 2, 4, 1, 1, 4, 4, 5, 4, 1, 4, 1, 3, 2, 2, 1],
    [21, 1,	1, 25, 4, 3, 1, 4, 4, 1, 2, 1, 1, 5, 2, 5, 1, 4, 4, 5],
    [17, 6, 1, 24, 3, 3, 1, 3, 5, 1, 1, 1, 2, 3, 1, 4, 1, 4, 5, 4],
    [5, 25, 0, 6, 1, 2, 5, 1, 1, 4, 4, 4, 5, 1, 4, 1, 3, 1, 1, 1],
    [2, 26, 0, 4, 1, 2, 5, 2, 1, 4, 4, 5, 4, 2, 5, 1, 3, 2, 2, 1],
    [4, 27, 0, 5, 1, 2, 4, 2, 1, 4, 4, 5, 5, 2, 5, 1, 3, 1, 2, 1],
    [1, 26, 0, 18, 2, 3, 3, 3, 1, 2, 2, 4, 3, 2, 1, 5, 1, 1, 5, 2],
    [18, 13, 1, 23, 3, 3, 1, 3, 5, 2, 1, 1, 2, 4, 2, 5, 1, 4, 4, 4],
    [17, 12, 1, 18, 4, 3, 1, 5, 4, 2, 1, 2, 1, 4, 1, 5, 1, 5, 4, 4],
    [9, 23, 1, 13, 3, 1, 3, 4, 3, 3, 2, 2, 3, 3, 3, 2, 2, 3, 2, 3]
    ]
)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([0, 2, 2, 0, 0, 0, 0, 2, 2, 1])